var languages = [
    'Albanés',
    'Alemán',
    'Amárico',
    'Árabe',
    'Azerí',
    'Bengalí',
    'Bielorruso',
    'Bislama',
    'Bislama',
    'Bosnio',
    'Búlgaro',
    'Canarés',
    'Catalán',
    'Checo',
    'Chino',
    'Coreano',
    'Creole',
    'Danés',
    'Dari',
    'Español',
    'Estonio',
    'Filipino',
    'Finlandés',
    'Fiyiano',
    'Francés',
    'Gaélico irlandés',
    'Georgiano',
    'Guaraní',
    'Hebreo',
    'Hebreo',
    'Inglés',
    'Italiano',
    'Jemer',
    'Kazajo',
    'Lenguaje de señas',
    'Macedonio',
    'Malayalam',
    'Malayo',
    'Maltés',
    'Moldavia',
    'Moldavia',
    'Mongol',
    'Montenegrino',
    'Ndebele',
    'Nepalí',
    'Norte de Sotho',
    'Noruego',
    'Oriya',
    'Pashto',
    'Portugués',
    'Punjabi',
    'Quechua',
    'Ruso',
    'Somalí',
    'Sotho',
    'Sueco',
    'Swati',
    'Tamil',
    'Telugu',
    'Tetum',
    'Tok Pisin',
    'Tsonga',
    'Tswana',
    'Zulú',
];



module.exports = languages;